### ISSUE TITLE
American and British English spelling differences

### ISSUE THREAD

**Issue by benmorrow** [raywenderlich/english-style-guide#10]
Ran into an editor changing recogn**ize** to recogn**ise**. _-ize_ is more common for Americans.

Perhaps this document can point out our preferred spelling for words with common spelling differences.

**Comment by greystar93** [comment]
That @micpringle ! You have to watch him closely. :] Though I'll always let him call me "Top Man".

**Comment by benmorrow** [comment]
Exonerate @micpringle because in this instance,@RuiAAPeres was my editor. I am grateful for his comprehensive reviews though. ;] @greystar93 You're everybody's top man.

**Comment by greystar93** [comment]
Aw, sorry @micpringle ! I guess we've badgered him enough. Time to buy him a well-deserved Imperial pint.

**Comment by rcritz** [comment]
Addressed in the guide now.
