### ISSUE TITLE
Control-Click or Control-click or control-click

### ISSUE THREAD

**Issue by jawwad** [raywenderlich/english-style-guide#2]
When spelling out shortcut keys the guide specifies that the modifiers should be capitalized: "Shift-Command-Option-X"

When referring to clicks, the guide specifies that "double-click" and "right-click" should be in lower case.

How should we capitalize control-drag and control-click?

Control-Click or Control-click or control-click
Control-Drag or Control-drag or control-drag

**Comment by crispy8888** [comment]
I vote for Control-click and Control-drag; that's how I've handled it for the last year or two. Also "Control-double-click" if it ever comes to that.

**Comment by greystar93** [comment]
Yeah, I do it the same as @crispy8888.

**Comment by jawwad** [comment]
I guess that makes sense to me now the "Control" is a or a proper noun and the "drag" is a verb. I'll add "Control-drag" and "Control-click" to the guide.

**Comment by jawwad** [comment]
Looks like I don't have direct edit access so opened a PR. I'll close this issue.
